import React,{useEffect,useMemo,useState} from 'react';
import toast from 'react-hot-toast';
import {inventoriesAPI} from '../lib/api';

const today=()=>new Date().toISOString().slice(0,10);
export default function InventoryPanel({ingredients,onRefresh}){
  const [sessions,setSessions]=useState([]),[active,setActive]=useState(null),[counts,setCounts]=useState({}),[kind,setKind]=useState('all'),[onlyDiff,setOnlyDiff]=useState(false),[saving,setSaving]=useState(false);
  const load=async()=>{try{const rows=await inventoriesAPI.getAll();setSessions(rows);const draft=rows.find(row=>row.status==='draft');if(draft){setActive(draft);setCounts(Object.fromEntries((draft.inventory_counts||[]).map(row=>[row.ingredient_id,row.counted_qty??''])));}}catch(e){toast.error(e.message);}};
  useEffect(()=>{load();},[]);
  const start=async()=>{setSaving(true);try{const session=await inventoriesAPI.create(ingredients,today());toast.success('Inventaire brouillon créé');setActive({...session,inventory_counts:[]});setCounts({});await load();}catch(e){toast.error(e.message);}finally{setSaving(false);}};
  const save=async()=>{if(!active)return;setSaving(true);try{await inventoriesAPI.saveCounts(active.id,counts);toast.success('Brouillon sauvegardé');await load();}catch(e){toast.error(e.message);}finally{setSaving(false);}};
  const validate=async()=>{if(!active)return;if(Object.keys(counts).length<ingredients.length||ingredients.some(i=>counts[i.id]===''))return toast.error('Comptez tous les articles avant validation');if(!window.confirm('Valider définitivement cet inventaire et corriger les stocks ?'))return;setSaving(true);try{await inventoriesAPI.saveCounts(active.id,counts);const result=await inventoriesAPI.validate(active.id);toast.success(`${result.adjustments} écart(s) validé(s) · ${Number(result.adjustment_value).toFixed(2)} DT`);setActive(null);setCounts({});await load();await onRefresh();}catch(e){toast.error(e.message);}finally{setSaving(false);}};
  const rows=useMemo(()=>ingredients.filter(i=>kind==='all'||(i.item_type||'raw_material')===kind).map(i=>{const counted=counts[i.id];const delta=counted===''||counted==null?null:Number(counted)-Number(i.stock_qty);return{...i,counted,delta,value:delta==null?0:Math.abs(delta)*Number(i.price_per_unit||0)};}).filter(i=>!onlyDiff||i.delta!==0),[ingredients,counts,kind,onlyDiff]);
  const totalValue=rows.reduce((sum,row)=>sum+row.value,0);
  return <div className="inventory-workspace">
    {!active?<><div className="inventory-empty card"><strong>Démarrer un inventaire</strong><span>Les stocks ne seront modifiés qu’après validation finale.</span><button className="btn btn-primary" disabled={saving} onClick={start}>Nouvel inventaire</button></div>{sessions.filter(s=>s.status==='validated').length>0&&<div className="card inventory-history"><div className="card-header"><div className="card-title">Historique des inventaires</div></div>{sessions.filter(s=>s.status==='validated').map(s=><article key={s.id}><strong>{new Date(`${s.inventory_date}T12:00:00`).toLocaleDateString('fr-FR')}</strong><span>{s.inventory_counts?.filter(c=>Number(c.counted_qty)!==Number(c.expected_qty)).length||0} écart(s)</span><small>Validé le {new Date(s.validated_at).toLocaleDateString('fr-FR')}</small></article>)}</div>}</>:
    <><div className="inventory-head"><div><strong>Inventaire du {new Date(`${active.inventory_date}T12:00:00`).toLocaleDateString('fr-FR')}</strong><small>Brouillon · sauvegardable sans modifier le stock</small></div><div><button className="btn" disabled={saving} onClick={save}>Sauvegarder</button><button className="btn btn-primary" disabled={saving} onClick={validate}>Valider l’inventaire</button></div></div>
    <div className="inventory-filters"><button className={kind==='all'?'active':''} onClick={()=>setKind('all')}>Tous</button><button className={kind==='raw_material'?'active':''} onClick={()=>setKind('raw_material')}>Matières</button><button className={kind==='consumable'?'active':''} onClick={()=>setKind('consumable')}>Consommables</button><label><input type="checkbox" checked={onlyDiff} onChange={e=>setOnlyDiff(e.target.checked)}/> Écarts uniquement</label><strong>{totalValue.toFixed(2)} DT d’écarts</strong></div>
    <div className="inventory-list">{rows.map(item=><div className="inventory-row" key={item.id}><div><strong>{item.name}</strong><small>Calculé : {item.stock_qty} {item.unit} · {item.value.toFixed(2)} DT d’écart</small></div><div className="inventory-input"><button onClick={()=>setCounts(v=>({...v,[item.id]:String(Math.max(0,Number(item.counted||0)-1))}))}>−</button><input type="number" min="0" value={item.counted??''} placeholder="Compter" onChange={e=>setCounts(v=>({...v,[item.id]:e.target.value}))}/><button onClick={()=>setCounts(v=>({...v,[item.id]:String(Number(item.counted||0)+1)}))}>+</button><span>{item.unit}</span></div><small className={item.delta===0?'':'changed'}>{item.delta==null?'À compter':item.delta===0?'Conforme':`${item.delta>0?'+':''}${item.delta} ${item.unit}`}</small></div>)}</div></>}
  </div>;
}
