import React,{useEffect,useMemo,useState} from 'react';
import toast from 'react-hot-toast';
import {subscriptionsAPI} from '../lib/api';
import {EmptyState,LoadingScreen,Modal,SectionHeader,SopGuide,VarietyDot} from '../components/UI';

const today=()=>new Date().toISOString().slice(0,10);
const empty=()=>({client:'',contact_email:'',contact_phone:'',deliveries_per_month:4,delivery_weekday:1,start_date:today(),end_date:'',status:'active',notes:'',items:[{variety_id:'',monthly_qty:100,price_per_unit:''}]});
const weekdays=['Lundi','Mardi','Mercredi','Jeudi','Vendredi','Samedi','Dimanche'];

export default function Subscriptions({varieties,onRefresh,onNavigate}){
  const [rows,setRows]=useState([]),[loading,setLoading]=useState(true),[open,setOpen]=useState(false),[form,setForm]=useState(empty()),[saving,setSaving]=useState(false),[generating,setGenerating]=useState(null),[deliveryDate,setDeliveryDate]=useState(today());
  const load=async()=>{setLoading(true);try{setRows(await subscriptionsAPI.getAll());}catch(e){toast.error(e.message);}finally{setLoading(false);}};
  useEffect(()=>{load();},[]);
  const active=rows.filter(row=>row.status==='active');
  const monthlyRevenue=active.reduce((sum,row)=>sum+(row.b2b_subscription_items||[]).reduce((s,item)=>s+Number(item.monthly_qty)*Number(item.price_per_unit),0),0);
  const monthlyUnits=active.reduce((sum,row)=>sum+(row.b2b_subscription_items||[]).reduce((s,item)=>s+Number(item.monthly_qty),0),0);
  const validItems=form.items.filter(item=>item.variety_id&&Number(item.monthly_qty)>0&&item.price_per_unit!=='');
  const formTotal=useMemo(()=>validItems.reduce((sum,item)=>sum+Number(item.monthly_qty)*Number(item.price_per_unit),0),[form.items]);
  const edit=row=>setForm({id:row.id,client:row.client,contact_email:row.contact_email||'',contact_phone:row.contact_phone||'',deliveries_per_month:row.deliveries_per_month,delivery_weekday:row.delivery_weekday,start_date:row.start_date,end_date:row.end_date||'',status:row.status,notes:row.notes||'',items:(row.b2b_subscription_items||[]).map(item=>({variety_id:item.variety_id,monthly_qty:item.monthly_qty,price_per_unit:item.price_per_unit}))}),openEditor=()=>{setForm(empty());setOpen(true);};
  const save=async()=>{if(!form.client.trim()||!validItems.length)return toast.error('Client et au moins un produit requis');setSaving(true);try{const{id,items,...header}=form;await subscriptionsAPI.save({...header,id:id||undefined,client:header.client.trim(),contact_email:header.contact_email||null,contact_phone:header.contact_phone||null,end_date:header.end_date||null,deliveries_per_month:Number(header.deliveries_per_month),delivery_weekday:Number(header.delivery_weekday)},validItems.map(item=>{const variety=varieties.find(v=>v.id===item.variety_id);return{variety_id:item.variety_id,variety_name:variety?.name||'',monthly_qty:Number(item.monthly_qty),price_per_unit:Number(item.price_per_unit)}}));toast.success('Forfait enregistré');setOpen(false);await load();}catch(e){toast.error(e.message);}finally{setSaving(false);}};
  const status=async(row,next)=>{try{await subscriptionsAPI.setStatus(row.id,next);toast.success(next==='active'?'Forfait activé':'Forfait mis en pause');await load();}catch(e){toast.error(e.message);}};
  const generate=async row=>{setGenerating(row.id);try{const order=await subscriptionsAPI.generateOrder(row.id,deliveryDate);toast.success(`Commande INS-${String(order.order_number).padStart(4,'0')} générée`);await load();onRefresh();}catch(e){toast.error(e.message);}finally{setGenerating(null);}};
  if(loading)return <LoadingScreen/>;
  return <div className="page-inner">
    <SectionHeader title="Abonnements B2B" subtitle="Forfaits mensuels des coffee shops et commandes récurrentes" actions={[<button key="new" className="btn btn-primary" onClick={openEditor}>+ Nouveau forfait</button>]}/>
    <SopGuide steps={[{title:'Contractualiser',detail:'Volume mensuel, prix et fréquence'},{title:'Générer',detail:'Créer chaque livraison dans Commandes'},{title:'Produire',detail:'Suivre le flux opérationnel habituel'}]}/>
    <div className="kpi-grid"><div className="kpi-card accent"><div className="kpi-label">Revenu mensuel prévu</div><div className="kpi-value">{monthlyRevenue.toFixed(2)}</div><div className="kpi-sub">DT</div></div><div className="kpi-card"><div className="kpi-label">Volume mensuel</div><div className="kpi-value">{monthlyUnits}</div><div className="kpi-sub">unités</div></div><div className="kpi-card success"><div className="kpi-label">Forfaits actifs</div><div className="kpi-value">{active.length}</div><div className="kpi-sub">clients</div></div></div>
    <div className="subscription-toolbar card"><label>Date de la prochaine livraison<input className="form-input" type="date" value={deliveryDate} onChange={e=>setDeliveryDate(e.target.value)}/></label><small>La commande générée apparaîtra dans Commandes et alimentera automatiquement Production et Achats.</small></div>
    {rows.length===0?<div className="card"><EmptyState text="Aucun forfait B2B. Créez le premier coffee shop partenaire."/></div>:<div className="subscription-grid">{rows.map(row=>{const items=row.b2b_subscription_items||[];const month=new Date().toISOString().slice(0,7);const monthOrders=(row.b2b_subscription_orders||[]).filter(link=>link.period_month?.startsWith(month));const ordered=monthOrders.reduce((sum,link)=>sum+(link.orders?.sales||[]).filter(s=>s.status!=='Annulée').reduce((n,s)=>n+Number(s.qty),0),0);const target=items.reduce((sum,item)=>sum+Number(item.monthly_qty),0);const revenue=items.reduce((sum,item)=>sum+Number(item.monthly_qty)*Number(item.price_per_unit),0);return <article className="card subscription-card" key={row.id}>
      <div className="subscription-head"><div><strong>{row.client}</strong><small>{row.contact_email||row.contact_phone||'Contact à compléter'}</small></div><span className={`badge ${row.status==='active'?'badge-ok':'badge-pending'}`}>{row.status==='active'?'Actif':'En pause'}</span></div>
      <div className="subscription-facts"><span><small>Forfait</small><b>{target} unités/mois</b></span><span><small>Livraisons</small><b>{row.deliveries_per_month}/mois · {weekdays[row.delivery_weekday-1]}</b></span><span><small>Montant</small><b>{revenue.toFixed(2)} DT</b></span></div>
      <div className="subscription-items">{items.map(item=>{const v=varieties.find(x=>x.id===item.variety_id);return <span key={item.id}><VarietyDot color={v?.color||'#999'}/><b>{item.variety_name}</b><small>{item.monthly_qty}/mois · {Number(item.price_per_unit).toFixed(3)} DT</small></span>})}</div>
      <div className="subscription-progress"><div><span style={{width:`${target?Math.min(100,ordered/target*100):0}%`}}/></div><small>{ordered} / {target} unités commandées ce mois · {monthOrders.length}/{row.deliveries_per_month} livraisons</small></div>
      <div className="subscription-actions"><button className="btn btn-sm" onClick={()=>{edit(row);setOpen(true)}}>Modifier</button><button className="btn btn-sm" onClick={()=>status(row,row.status==='active'?'paused':'active')}>{row.status==='active'?'Mettre en pause':'Réactiver'}</button>{row.status==='active'&&<button className="btn btn-sm btn-primary" disabled={generating===row.id} onClick={()=>generate(row)}>{generating===row.id?'Génération...':'Générer la commande'}</button>}{monthOrders.length>0&&<button className="btn btn-sm" onClick={()=>onNavigate('sales')}>Voir commandes</button>}</div>
    </article>})}</div>}
    <Modal open={open} onClose={()=>setOpen(false)} size="lg" title={form.id?'Modifier le forfait':'Nouveau forfait B2B'} footer={<><button className="btn" onClick={()=>setOpen(false)}>Annuler</button><button className="btn btn-primary" disabled={saving} onClick={save}>{saving?'Enregistrement...':'Enregistrer'}</button></>}>
      <div className="form-row form-row-2"><div className="form-group"><label className="form-label">Coffee shop / client *</label><input className="form-input" value={form.client} onChange={e=>setForm(v=>({...v,client:e.target.value}))}/></div><div className="form-group"><label className="form-label">E-mail</label><input className="form-input" type="email" value={form.contact_email} onChange={e=>setForm(v=>({...v,contact_email:e.target.value}))}/></div></div>
      <div className="form-row form-row-3"><div className="form-group"><label className="form-label">Téléphone</label><input className="form-input" value={form.contact_phone} onChange={e=>setForm(v=>({...v,contact_phone:e.target.value}))}/></div><div className="form-group"><label className="form-label">Livraisons/mois</label><select className="form-select" value={form.deliveries_per_month} onChange={e=>setForm(v=>({...v,deliveries_per_month:e.target.value}))}><option value="1">1 · mensuelle</option><option value="2">2 · bimensuelle</option><option value="4">4 · hebdomadaire</option></select></div><div className="form-group"><label className="form-label">Jour habituel</label><select className="form-select" value={form.delivery_weekday} onChange={e=>setForm(v=>({...v,delivery_weekday:e.target.value}))}>{weekdays.map((day,i)=><option value={i+1} key={day}>{day}</option>)}</select></div></div>
      <div className="form-row form-row-2"><div className="form-group"><label className="form-label">Début</label><input className="form-input" type="date" value={form.start_date} onChange={e=>setForm(v=>({...v,start_date:e.target.value}))}/></div><div className="form-group"><label className="form-label">Fin facultative</label><input className="form-input" type="date" value={form.end_date} onChange={e=>setForm(v=>({...v,end_date:e.target.value}))}/></div></div>
      <div className="subscription-editor"><div className="order-editor-head"><strong>Produits du forfait</strong><button className="btn btn-sm" onClick={()=>setForm(v=>({...v,items:[...v.items,{variety_id:'',monthly_qty:100,price_per_unit:''}]}))}>+ Produit</button></div>{form.items.map((item,index)=><div className="subscription-editor-line" key={index}><select className="form-select" value={item.variety_id} onChange={e=>setForm(v=>({...v,items:v.items.map((x,i)=>i===index?{...x,variety_id:e.target.value,price_per_unit:varieties.find(p=>p.id===e.target.value)?.sale_prices?.find(p=>p.canal==='B2B')?.price??x.price_per_unit}:x)}))}><option value="">Choisir...</option>{varieties.filter(v=>v.product_status!=='draft').map(v=><option value={v.id} key={v.id}>{v.name}</option>)}</select><input className="form-input" type="number" min="1" value={item.monthly_qty} onChange={e=>setForm(v=>({...v,items:v.items.map((x,i)=>i===index?{...x,monthly_qty:e.target.value}:x)}))} placeholder="Qté/mois"/><input className="form-input" type="number" min="0" step="0.001" value={item.price_per_unit} onChange={e=>setForm(v=>({...v,items:v.items.map((x,i)=>i===index?{...x,price_per_unit:e.target.value}:x)}))} placeholder="Prix/u"/><button className="btn btn-icon btn-ghost" onClick={()=>setForm(v=>({...v,items:v.items.filter((_,i)=>i!==index)}))}>×</button></div>)}</div>
      <div className="form-group"><label className="form-label">Notes</label><textarea className="form-textarea" rows="2" value={form.notes} onChange={e=>setForm(v=>({...v,notes:e.target.value}))}/></div><div className="order-total"><span>Montant mensuel prévu <strong>{formTotal.toFixed(3)} DT</strong></span></div>
    </Modal>
  </div>;
}
